on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        # uses: crazy-max/ghaction-docker-buildx@v1
        uses: docker/setup-buildx-action@v1       
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build \
          --platform linux/arm64  \
          --tag andrewcstewart/arrow-arm \
          --file ./arrow-arm64/Dockerfile .