on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        # uses: crazy-max/ghaction-docker-buildx@v1
        uses: docker/setup-buildx-action@v1       
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}          
      - name: build the image
        run: |
          docker buildx build \
          --platform linux/arm64  \
          --tag andrewcstewart/superset-arm \
          --output "type=image,push=true" \          
          --file ./superset-arm64/Dockerfile .
      - name: Inspect image
        run: |
          docker buildx imagetools inspect andrewcstewart/superset-arm:latest      